package com.kotlin.todo.config

import io.r2dbc.spi.ConnectionFactory
import org.springframework.boot.CommandLineRunner
import org.springframework.context.annotation.Bean
import org.springframework.stereotype.Component
import reactor.core.publisher.Flux


@Component
class InitializerConfiguration {


    @Bean
    fun initDB(connectionFactory: ConnectionFactory): CommandLineRunner {
        return CommandLineRunner {
            Flux.from(connectionFactory.create())
                    .flatMap { conn ->
                        Flux.from(conn.createBatch()
                                .add("drop table if exists todos")
                                .add("create table todos ( id bigint generated by default as identity, content varchar(2000),created_at timestamp, done boolean, modified_at timestamp, primary key (id))")
                                .execute()
                        ).doFinally({ conn.close() })
                    }
                    .log()
                    .blockLast()
        }
    }

}